spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_web
    username: root
    password: 12345678
  mail:
    host: smtp.gmail.com

    username: edwinzhanofficialnonreply@gmail.com
    password: hjlj nrsd qwxo trwn
    port: 465
    properties:
      from: edwinzhanofficialnonreply@gmail.com
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  azure:
    storage:
      connection-string: DefaultEndpointsProtocol=https;AccountName=edwinzhan;AccountKey=PacvWriDCVYmFze/WEnxsfxLQhuacHnjg8ITz0rpU8pmHPVd0JhmLQ4cIQOFfq6NABqe8/rIfUKp+AStdnH9aw==;EndpointSuffix=core.windows.net
      container-name: web-app
#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    org.apache.coyote.http11.Http11Processor: DEBUG