spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_web
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.apache.coyote.http11.Http11Processor: DEBUG

